[tool.poetry]
name = "scanbot"
version = "0.1.0"
description = ""
authors = ["Akhil Anilkumar <akhil.anilkumar@cubettech.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.13"
uvicorn = "^0.34.3"
python-dotenv = "^1.1.0"
llama-parse = "^0.6.34"
langchain-chroma = "^0.2.4"
langgraph = "^0.4.8"
langchain-openai = "^0.3.24"
langchain-community = "^0.3.25"
python-multipart = "^0.0.20"
streamlit = "^1.46.0"
protobuf = "3.20"
chromadb = "^1.0.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
